<?php

namespace QServer\Commands;

/**
 * Show help info
 */
class HelpCommand implements CommandInterface
{
    /**
     * Command signature for call in cli
     *
     * @var string
     */
    public static $signature = 'help';

    /**
     * @inheritDoc
     */
    public function run($data = [])
    {
        return PHP_EOL."Q-Server - simple jobs queue for easy projects like a home server".PHP_EOL.PHP_EOL.
            "use php for run file e.g. php {".__START_SCRIPT__."/q-server.php} put --cmd='cd path/to/project/ && php command.php' --comment='run my command'".PHP_EOL.PHP_EOL.
            "put - put job to queue".PHP_EOL
            . "    --cmd         - command for run on ".PHP_EOL
            . "    --comment     - just comment for list command ".PHP_EOL
            . "    --id          - command id. optional. by default generated by script ".PHP_EOL
            . "    --delay       - delay before run in seconds. default is 0 ".PHP_EOL
            . "    --tries       - tries for run before kill job. default is 1 ".PHP_EOL
            . "    --tries_delay - delay between tries in seconds. default is 180 (3 min)".PHP_EOL;
    }

    /**
     * @inheritDoc
     */
    public function isValid($data = []) : bool
    {
        return true;
    }
}